### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by laurosilvacom** [laurosilvacom/awesomecheatsheets#1]
## TODO

Here's what's missing in the repo: 

- [x] How to contribute
- [x] Add All Contributorsrc
- [x] Issue/PR template
- [x] Code of conduct 

Feel free to open an issue to start collaborating. 🙌

**Comment by laurosilvacom** [comment]
@all-contributors please add @laurosilvacom  for content doc maintenance review
